package users

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/http"
	"net/url"

	"github.com/antiwork/gumroad-cli/internal/adminapi"
	"github.com/antiwork/gumroad-cli/internal/admincmd"
	"github.com/antiwork/gumroad-cli/internal/cmdutil"
	"github.com/antiwork/gumroad-cli/internal/output"
	"github.com/spf13/cobra"
)

type addCommentRequest struct {
	Email          string `json:"email,omitempty"`
	ExternalID     string `json:"external_id,omitempty"`
	Content        string `json:"content"`
	IdempotencyKey string `json:"idempotency_key"`
}

type addCommentResponse struct {
	Comment commentPayload `json:"comment"`
}

type commentPayload struct {
	ID          string `json:"id"`
	AuthorName  string `json:"author_name"`
	Content     string `json:"content"`
	CommentType string `json:"comment_type"`
	CreatedAt   string `json:"created_at"`
}

func newAddCommentCmd() *cobra.Command {
	var (
		email          string
		externalID     string
		content        string
		idempotencyKey string
	)

	cmd := &cobra.Command{
		Use:   "add-comment",
		Short: "Add an admin note to a user's record",
		Long: `Add an admin note to a user's record.

The note is stored as a comment with type "Note". --idempotency-key
guarantees that retrying the same call does not create duplicate notes;
when omitted, a fresh key is generated and printed to stderr so an
operator can rerun the same command if a transient failure occurs.

Identify the user with --email or --external-id. When both are supplied,
the server resolves by --external-id.`,
		Example: `  gumroad admin users add-comment --email user@example.com --content "VAT exempt confirmed"
  gumroad admin users add-comment --external-id 2245593582708 --content "VAT exempt confirmed"
  gumroad admin users add-comment --email user@example.com --content "..." --idempotency-key 8f3a...`,
		Args: cmdutil.ExactArgs(0),
		RunE: func(c *cobra.Command, args []string) error {
			opts := cmdutil.OptionsFrom(c)
			if err := requireEmailOrExternalID(c, email, externalID); err != nil {
				return err
			}
			if content == "" {
				return cmdutil.MissingFlagError(c, "--content")
			}

			autogenerated := false
			if idempotencyKey == "" {
				key, err := generateIdempotencyKey()
				if err != nil {
					return fmt.Errorf("could not generate idempotency key: %w", err)
				}
				idempotencyKey = key
				autogenerated = true
			}

			identifier := userIdentifier(email, externalID)
			ok, err := cmdutil.ConfirmAction(opts, "Add admin note to "+identifier+"?")
			if err != nil {
				return err
			}
			if !ok {
				return cmdutil.PrintCancelledAction(opts, "add comment for "+identifier, identifier)
			}

			req := addCommentRequest{Email: email, ExternalID: externalID, Content: content, IdempotencyKey: idempotencyKey}

			if opts.DryRun {
				params := url.Values{}
				if email != "" {
					params.Set("email", email)
				}
				if externalID != "" {
					params.Set("external_id", externalID)
				}
				params.Set("content", content)
				if autogenerated {
					params.Set("idempotency_key", "<auto-generated, regenerated on real call>")
				} else {
					params.Set("idempotency_key", idempotencyKey)
				}
				return cmdutil.PrintDryRunRequest(opts, http.MethodPost, adminapi.AdminPath("/users/create_comment"), params)
			}

			if autogenerated {
				_, _ = fmt.Fprintf(opts.Err(), "Idempotency key: %s\n", idempotencyKey)
			}

			data, err := admincmd.FetchPostJSON(opts, "Adding comment...", "/users/create_comment", req)
			if err != nil {
				return err
			}

			if opts.UsesJSONOutput() {
				return cmdutil.PrintJSONResponse(opts, data)
			}

			decoded, err := cmdutil.DecodeJSON[addCommentResponse](data)
			if err != nil {
				return err
			}
			return renderAddComment(opts, identifier, decoded)
		},
	}

	cmd.Flags().StringVar(&email, "email", "", "User email")
	cmd.Flags().StringVar(&externalID, "external-id", "", "User external ID")
	cmd.Flags().StringVar(&content, "content", "", "Comment text (required)")
	cmd.Flags().StringVar(&idempotencyKey, "idempotency-key", "", "Idempotency key (auto-generated when omitted)")

	return cmd
}

func generateIdempotencyKey() (string, error) {
	const idempotencyKeyBytes = 16
	buf := make([]byte, idempotencyKeyBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func renderAddComment(opts cmdutil.Options, identifier string, resp addCommentResponse) error {
	message := "Added admin note to " + identifier
	commentType := resp.Comment.CommentType
	if commentType == "" {
		commentType = "Note"
	}

	if opts.PlainOutput {
		return output.PrintPlain(opts.Out(), [][]string{
			{"true", message, identifier, resp.Comment.ID, commentType, resp.Comment.CreatedAt},
		})
	}

	if opts.Quiet {
		return nil
	}

	if err := output.Writeln(opts.Out(), opts.Style().Green(message)); err != nil {
		return err
	}
	if resp.Comment.ID != "" {
		if err := output.Writef(opts.Out(), "Comment ID: %s\n", resp.Comment.ID); err != nil {
			return err
		}
	}
	if resp.Comment.AuthorName != "" {
		if err := output.Writef(opts.Out(), "Author: %s\n", resp.Comment.AuthorName); err != nil {
			return err
		}
	}
	if resp.Comment.CreatedAt != "" {
		return output.Writef(opts.Out(), "Created: %s\n", resp.Comment.CreatedAt)
	}
	return nil
}
