#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 ]]; then
    echo "usage: $0 <tag> <checksums.txt> <output-formula>" >&2
    exit 1
fi

TAG=$1
CHECKSUMS_FILE=$2
OUTPUT_FILE=$3

PROJECT_NAME="gumroad-cli"
REPOSITORY="antiwork/gumroad-cli"

display_version() {
    local version=${1#v}

    if [[ $version =~ ^0\.([0-9]{4})([0-9]{2})([0-9]{2})\.([0-9]+)$ ]]; then
        local year="${BASH_REMATCH[1]}"
        local month="${BASH_REMATCH[2]}"
        local day="${BASH_REMATCH[3]}"
        local sequence="${BASH_REMATCH[4]}"
        if valid_date "$year" "$month" "$day"; then
            local display="${year}.${month}.${day}"
            if [[ "$sequence" != "0" ]]; then
                display="${display}.${sequence}"
            fi
            printf '%s\n' "$display"
            return
        fi
    fi

    printf '%s\n' "$version"
}

valid_date() {
    local year=$1
    local month=$2
    local day=$3
    local year_num=$((10#$year))
    local month_num=$((10#$month))
    local day_num=$((10#$day))

    if (( month_num < 1 || month_num > 12 )); then
        return 1
    fi

    local days_in_month=(0 31 28 31 30 31 30 31 31 30 31 30 31)
    if (( month_num == 2 && (year_num % 400 == 0 || (year_num % 4 == 0 && year_num % 100 != 0)) )); then
        days_in_month[2]=29
    fi

    (( day_num >= 1 && day_num <= days_in_month[month_num] ))
}

VERSION="$(display_version "$TAG")"

checksum_for() {
    local archive=$1
    local checksum

    checksum=$(awk -v file="$archive" '$2 == file || $2 == ("*" file) { print $1; exit }' "$CHECKSUMS_FILE")
    if [[ -z "$checksum" ]]; then
        echo "missing checksum for ${archive} in ${CHECKSUMS_FILE}" >&2
        exit 1
    fi

    printf '%s\n' "$checksum"
}

archive_url() {
    local os=$1
    local arch=$2

    printf 'https://github.com/%s/releases/download/%s/%s_%s_%s.tar.gz' \
        "$REPOSITORY" "$TAG" "$PROJECT_NAME" "$os" "$arch"
}

darwin_arm64_sha=$(checksum_for "${PROJECT_NAME}_darwin_arm64.tar.gz")
darwin_amd64_sha=$(checksum_for "${PROJECT_NAME}_darwin_amd64.tar.gz")
linux_arm64_sha=$(checksum_for "${PROJECT_NAME}_linux_arm64.tar.gz")
linux_amd64_sha=$(checksum_for "${PROJECT_NAME}_linux_amd64.tar.gz")

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat >"$OUTPUT_FILE" <<EOF
# This file is generated by script/render-homebrew-formula.sh. DO NOT EDIT.
class Gumroad < Formula
  desc "CLI for the Gumroad API"
  homepage "https://github.com/${REPOSITORY}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "$(archive_url darwin arm64)"
      sha256 "${darwin_arm64_sha}"
    end
    on_intel do
      url "$(archive_url darwin amd64)"
      sha256 "${darwin_amd64_sha}"
    end
  end

  on_linux do
    on_arm do
      url "$(archive_url linux arm64)"
      sha256 "${linux_arm64_sha}"
    end
    on_intel do
      url "$(archive_url linux amd64)"
      sha256 "${linux_amd64_sha}"
    end
  end

  def install
    bin.install "gumroad"
    man1.install Dir["man/*.1"]
    generate_completions_from_executable(bin/"gumroad", "completion")
    (pwsh_completion/"gumroad.ps1").write Utils.safe_popen_read(bin/"gumroad", "completion", "powershell")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gumroad --version")
  end
end
EOF
